In [0]:
!pip install pandas

Requirement already satisfied: pandas in /databricks/python3/lib/python3.12/site-packages (1.5.3)
Requirement already satisfied: numpy>=1.21.0 in /databricks/python3/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /databricks/python3/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /databricks/python3/lib/python3.12/site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
import pandas as pd

In [0]:

players_df = pd.read_csv("https://raw.githubusercontent.com/ritesh-ojha/IPL-DATASET/refs/heads/main/csv/2024_players_details.csv")

In [0]:
players_df.head()

       ID  ...                                           espn_url
0   95094  ...  https://www.espncricinfo.com/cricketers/rutura...
1   46597  ...  https://www.espncricinfo.com/cricketers/moeen-...
2  116328  ...  https://www.espncricinfo.com/cricketers/aravel...
3   62022  ...  https://www.espncricinfo.com/cricketers/deepak...
4   80607  ...  https://www.espncricinfo.com/cricketers/tushar...

[5 rows x 13 columns]

In [0]:
ball_by_ball_df = pd.read_csv("https://raw.githubusercontent.com/ritesh-ojha/IPL-DATASET/refs/heads/main/csv/Ball_By_Ball_Match_Data.csv")

In [0]:
ball_by_ball_df.head()

       ID  Innings  Overs  ...  Kind FieldersInvolved     BattingTeam
0  336036        1      0  ...   NaN              NaN  Mumbai Indians
1  336036        1      0  ...   NaN              NaN  Mumbai Indians
2  336036        1      0  ...   NaN              NaN  Mumbai Indians
3  336036        1      0  ...   NaN              NaN  Mumbai Indians
4  336036        1      0  ...   NaN              NaN  Mumbai Indians

[5 rows x 16 columns]

In [0]:
match_info_df = pd.read_csv("https://raw.githubusercontent.com/ritesh-ojha/IPL-DATASET/refs/heads/main/csv/Match_Info.csv")

In [0]:
match_info_df.head()

   match_number  ...                                      team2_players
0        336036  ...  ST Jayasuriya, SR Tendulkar, AM Nayar, RV Utha...
1        335995  ...  G Gambhir, V Sehwag, S Dhawan, Shoaib Malik, M...
2       1254108  ...  RG Sharma, Q de Kock, Ishan Kishan, SA Yadav, ...
3        829761  ...  MK Tiwary, SS Iyer, JP Duminy, KM Jadhav, Yuvr...
4       1216521  ...  Q de Kock, Ishan Kishan, SA Yadav, SS Tiwary, ...

[5 rows x 14 columns]

In [0]:
teams_df = pd.read_csv("https://raw.githubusercontent.com/ritesh-ojha/IPL-DATASET/refs/heads/main/csv/teams_info.csv")

In [0]:
teams_df.head()

                    team_name  ... espn_id
0              Mumbai Indians  ...    4346
1         Chennai Super Kings  ...    4343
2              Delhi Capitals  ...    4347
3  Kolkata Knight Respn_iders  ...    4341
4                Punjab Kings  ...    4342

[5 rows x 3 columns]

In [0]:
#manual data profing
print(players_df.info())
print(ball_by_ball_df.info())
print(match_info_df.info())
print(teams_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 261 entries, 0 to 260
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID                 261 non-null    int64
 1   Name               261 non-null    object
 2   longName           261 non-null    object
 3   battingName        261 non-null    object
 4   fieldingName       261 non-null    object
 5   imgUrl             261 non-null    object
 6   dob                261 non-null    object
 7   battingStyles      261 non-null    object
 8   longBattingStyles  261 non-null    object
 9   bowlingStyles      261 non-null    object
 10  longBowlingStyles  261 non-null    object
 11  playingRoles       237 non-null    object
 12  espn_url           261 non-null    object
dtypes: int64(1), object(12)
memory usage: 26.6+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278205 entries, 0 to 278204
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   ID                278205 non-null  int64
 1   Innings           278205 non-null  int64
 2   Overs             278205 non-null  int64
 3   BallNumber        278205 non-null  int64
 4   Batter            278205 non-null  object
 5   Bowler            278205 non-null  object
 6   NonStriker        278205 non-null  object
 7   ExtraType         15133 non-null   object
 8   BatsmanRun        278205 non-null  int64
 9   ExtrasRun         278205 non-null  int64
 10  TotalRun          278205 non-null  int64
 11  IsWicketDelivery  278205 non-null  int64
 12  PlayerOut         13823 non-null   object
 13  Kind              13823 non-null   object
 14  FieldersInvolved  10013 non-null   object
 15  BattingTeam       278205 non-null  object
dtypes: int64(8), object(8)
memory usage: 34.0+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1169 entries, 0 to 1168
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   match_number     1169 non-null   int64
 1   team1            1169 non-null   object
 2   team2            1169 non-null   object
 3   match_date       1169 non-null   object
 4   toss_winner      1169 non-null   object
 5   toss_decision    1169 non-null   object
 6   result           1169 non-null   object
 7   eliminator       15 non-null     object
 8   winner           1146 non-null   object
 9   player_of_match  1169 non-null   object
 10  venue            1169 non-null   object
 11  city             1118 non-null   object
 12  team1_players    1169 non-null   object
 13  team2_players    1169 non-null   object
dtypes: int64(1), object(13)
memory usage: 128.0+ KB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   team_name  19 non-null     object
 1   url        19 non-null     object
 2   espn_id    19 non-null     int64
dtypes: int64(1), object(2)
memory usage: 588.0+ bytes
None

In [0]:
# Missing values count
print(players_df.isnull().sum())

# Percentage of missing values
print((players_df.isnull().sum() / len(players_df)) * 100)

# Duplicates
print(players_df.duplicated().sum())

ID                    0
Name                  0
longName              0
battingName           0
fieldingName          0
imgUrl                0
dob                   0
battingStyles         0
longBattingStyles     0
bowlingStyles         0
longBowlingStyles     0
playingRoles         24
espn_url              0
dtype: int64
ID                   0.000000
Name                 0.000000
longName             0.000000
battingName          0.000000
fieldingName         0.000000
imgUrl               0.000000
dob                  0.000000
battingStyles        0.000000
longBattingStyles    0.000000
bowlingStyles        0.000000
longBowlingStyles    0.000000
playingRoles         9.195402
espn_url             0.000000
dtype: float64
0

In [0]:
#handing null values in players_df
#dropping columns with more than 50% null values
players_df.fillna(players_df.mode().iloc[0], inplace=True)
print(players_df.isnull().sum())

ID                   0
Name                 0
longName             0
battingName          0
fieldingName         0
imgUrl               0
dob                  0
battingStyles        0
longBattingStyles    0
bowlingStyles        0
longBowlingStyles    0
playingRoles         0
espn_url             0
dtype: int64

In [0]:
# Missing values count - 
print(ball_by_ball_df.isnull().sum())

# Percentage of missing values
print((ball_by_ball_df.isnull().sum() / len(ball_by_ball_df)) * 100)

# Duplicates
print(ball_by_ball_df.duplicated().sum())

ID                       0
Innings                  0
Overs                    0
BallNumber               0
Batter                   0
Bowler                   0
NonStriker               0
ExtraType           263072
BatsmanRun               0
ExtrasRun                0
TotalRun                 0
IsWicketDelivery         0
PlayerOut           264382
Kind                264382
FieldersInvolved    268192
BattingTeam              0
dtype: int64
ID                   0.000000
Innings              0.000000
Overs                0.000000
BallNumber           0.000000
Batter               0.000000
Bowler               0.000000
NonStriker           0.000000
ExtraType           94.560486
BatsmanRun           0.000000
ExtrasRun            0.000000
TotalRun             0.000000
IsWicketDelivery     0.000000
PlayerOut           95.031362
Kind                95.031362
FieldersInvolved    96.400855
BattingTeam          0.000000
dtype: float64
0

In [0]:
#handing null values in players_df
#dropping columns with more than 50% null values
ball_by_ball_df.fillna(ball_by_ball_df.mode().iloc[0], inplace=True)
print(ball_by_ball_df.isnull().sum())

ID                  0
Innings             0
Overs               0
BallNumber          0
Batter              0
Bowler              0
NonStriker          0
ExtraType           0
BatsmanRun          0
ExtrasRun           0
TotalRun            0
IsWicketDelivery    0
PlayerOut           0
Kind                0
FieldersInvolved    0
BattingTeam         0
dtype: int64

In [0]:

# Missing values count - 
print(match_info_df.isnull().sum())

# Percentage of missing values
print((match_info_df.isnull().sum() / len(match_info_df)) * 100)

# Duplicates
print(match_info_df.duplicated().sum())

match_number          0
team1                 0
team2                 0
match_date            0
toss_winner           0
toss_decision         0
result                0
eliminator         1154
winner               23
player_of_match       0
venue                 0
city                 51
team1_players         0
team2_players         0
dtype: int64
match_number        0.000000
team1               0.000000
team2               0.000000
match_date          0.000000
toss_winner         0.000000
toss_decision       0.000000
result              0.000000
eliminator         98.716852
winner              1.967494
player_of_match     0.000000
venue               0.000000
city                4.362703
team1_players       0.000000
team2_players       0.000000
dtype: float64
0

In [0]:
#handing null values in players_df
#dropping columns with more than 50% null values
match_info_df.fillna(match_info_df.mode().iloc[0], inplace=True)
print(match_info_df.isnull().sum())

match_number       0
team1              0
team2              0
match_date         0
toss_winner        0
toss_decision      0
result             0
eliminator         0
winner             0
player_of_match    0
venue              0
city               0
team1_players      0
team2_players      0
dtype: int64

In [0]:

# Missing values count - 
print(teams_df.isnull().sum())

# Percentage of missing values
print((teams_df.isnull().sum() / len(teams_df)) * 100)

# Duplicates
print(teams_df.duplicated().sum())

team_name    0
url          0
espn_id      0
dtype: int64
team_name    0.0
url          0.0
espn_id      0.0
dtype: float64
0

In [0]:
from ydata_profiling import ProfileReport

In [0]:
player_profile = ProfileReport(players_df, title="IPL Players Profiling Report", explorative=True)

In [0]:
%pip install sweetviz
import sweetviz as sv

Collecting sweetviz
  Downloading sweetviz-2.3.1-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from sweetviz) (2.2.2)
Requirement already satisfied: numpy>=1.16.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from sweetviz) (2.1.3)
Requirement already satisfied: matplotlib>=3.1.3 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from sweetviz) (3.9.4)
Requirement already satisfied: tqdm>=4.43.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from sweetviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from sweetviz) (1.13.1)
Requirement already satisfied: jinja2>=2.11.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from sweetviz) (3.1.6)
Collecting importlib-resources>=1.2.0 (from sweetviz)
  Downloading importlib_resources-6.5.2-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: MarkupSafe>=2.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from jinja2>=2.11.1->sweetviz) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from matplotlib>=3.1.3->sweetviz) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from matplotlib>=3.1.3->sweetviz) (4.59.2)
Requirement already satisfied: kiwisolver>=1.3.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from matplotlib>=3.1.3->sweetviz) (25.0)
Requirement already satisfied: pillow>=8 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from matplotlib>=3.1.3->sweetviz) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from matplotlib>=3.1.3->sweetviz) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: six>=1.5 in /local_disk0/.ephemeral_nfs/envs/pythonEnv-b4db34aa-3b71-495a-900e-87f96b35b5da/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Downloading sweetviz-2.3.1-py3-none-any.whl (15.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB 98.9 MB/s eta 0:00:00
Downloading importlib_resources-6.5.2-py3-none-any.whl (37 kB)
Installing collected packages: importlib-resources, sweetviz
Successfully installed importlib-resources-6.5.2 sweetviz-2.3.1
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.

In [0]:
report = sv.analyze(players_df)

                                             |          | [  0%]   00:00 -> (? left)

In [0]:
report.show_html("players_df.html")

Report players_df.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [0]:
report.show_html("players_df.pdf")

Report players_df.pdf was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [0]:
report_ball_by_ball_df = sv.analyze(ball_by_ball_df)

                                             |          | [  0%]   00:00 -> (? left)

In [0]:
report_ball_by_ball_df.show_html("report_ball_by_ball_df.html")

Report report_ball_by_ball_df.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [0]:
report_ball_by_ball_df.show_html("report_ball_by_ball_df.pdf")

Report report_ball_by_ball_df.pdf was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [0]:
report_match_info_df = sv.analyze(match_info_df)

                                             |          | [  0%]   00:00 -> (? left)

In [0]:
report_match_info_df.show_html("report_match_info_df.pdf")

Report report_match_info_df.pdf was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [0]:
report_teams_df = sv.analyze(teams_df)

                                             |          | [  0%]   00:00 -> (? left)

In [0]:
report_teams_df.show_html("report_teams_df.pdf")

Report report_teams_df.pdf was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

Problem Statement 1: Top 10 Batsmen by Runs

In [0]:
top_batsmen = (
    ball_by_ball_df.groupby("Batter")["BatsmanRun"]
    .sum()
    .reset_index()
    .sort_values(by="BatsmanRun", ascending=False)
    .head(10)
)
print(top_batsmen)

             Batter  BatsmanRun
658         V Kohli        8671
500       RG Sharma        7048
535        S Dhawan        6769
151       DA Warner        6567
569        SK Raina        5536
389        MS Dhoni        5439
297        KL Rahul        5235
31   AB de Villiers        5181
51        AM Rahane        5032
128        CH Gayle        4997

Problem Statement 2: Teams with Most Wins

In [0]:
team_wins = (
    match_info_df.groupby("winner")["match_number"]  # match_number as unique match ID
    .count()
    .reset_index()
    .rename(columns={"match_number": "wins"})
    .sort_values(by="wins", ascending=False)
)
print(team_wins)

                         winner  wins
10               Mumbai Indians   174
0           Chennai Super Kings   142
8         Kolkata Knight Riders   135
16  Royal Challengers Bangalore   114
13             Rajasthan Royals   114
18          Sunrisers Hyderabad    93
6               Kings XI Punjab    85
3              Delhi Daredevils    67
2                Delhi Capitals    51
5                Gujarat Titans    37
12                 Punjab Kings    34
9          Lucknow Super Giants    30
1               Deccan Chargers    29
17  Royal Challengers Bengaluru    18
4                 Gujarat Lions    13
11                Pune Warriors    12
14       Rising Pune Supergiant    10
7          Kochi Tuskers Kerala     6
15      Rising Pune Supergiants     5

Statement 3: Top 10 Most Valuable Players (MVPs) by Player of the Match Awards

In [0]:
top_mvp = (
    match_info_df.groupby("player_of_match")["match_number"]
    .count()
    .reset_index()
    .rename(columns={"match_number": "awards"})
    .sort_values(by="awards", ascending=False)
    .head(10)
)
print(top_mvp)

    player_of_match  awards
11   AB de Villiers      25
46         CH Gayle      22
228       RG Sharma      21
292         V Kohli      19
57        DA Warner      18
174        MS Dhoni      18
263       SP Narine      17
222       RA Jadeja      16
266       SR Watson      16
16       AD Russell      16